# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='point',
            field=models.FileField(default=1, upload_to=b'social/point', verbose_name=''),
            preserve_default=False,
        ),
    ]
