# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_objects', '0003_auto_20160425_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSocialHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to=b'social-hub/image', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='SocialHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to=b'social-hub/cover/', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430')),
                ('title', models.CharField(max_length=500, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('phone', models.CharField(max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430')),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='\u0414\u043e\u043b\u0433\u043e\u0442\u0430')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctaegory_objects', to='social_objects.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
        ),
        migrations.RemoveField(
            model_name='socialobject',
            name='category',
        ),
        migrations.DeleteModel(
            name='SocialObject',
        ),
        migrations.AddField(
            model_name='imagesocialhub',
            name='social_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social_objects.SocialHub', verbose_name=''),
        ),
    ]
