# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_objects', '0004_auto_20160426_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialhub',
            options={'verbose_name': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0439 \u0446\u0435\u043d\u0442\u0440', 'verbose_name_plural': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0446\u0435\u043d\u0442\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='socialhub',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialhub',
            name='bank',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0411\u0430\u043d\u043a'),
        ),
        migrations.AddField(
            model_name='socialhub',
            name='personal_account',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041b\u0438\u0446\u0435\u0432\u043e\u0439 \u0441\u0447\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='socialhub',
            name='special_account',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0421\u043f\u0435\u0446. \u0441\u0447\u0435\u0442'),
        ),
    ]
